package org.freeone.swing;

import com.intellij.openapi.wm.ToolWindow;
import com.intellij.openapi.wm.ToolWindowManager;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class JBeantoTsBeanFolderMapTablePanel {
    public JPanel folderMapPanel;
    private JButton addButton;
    private JButton removeButton;
    private JTable table1;
    private JTextField textField1;

    public JBeantoTsBeanFolderMapTablePanel() {
        $$$setupUI$$$();
        addButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);

                table1.setModel(new DefaultTableModel(
                        new Object[][]{
                                {2, 2},
                                {12, 2},
                                {12, 2},
                                {12, 2},
                                {12, 2},
                                {12, 2},
                        },
                        new String[]{
                                "Java\u6E90\u8DEF\u5F84", "TypeScript\u76EE\u6807\u8DEF\u5F84"
                        }
                ));




            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("JBeantoTsBeanFolderMapTablePanel");
        frame.setContentPane(new JBeantoTsBeanFolderMapTablePanel().folderMapPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        folderMapPanel = new JPanel();
        folderMapPanel.setLayout(new GridLayoutManager(3, 4, new Insets(0, 0, 0, 0), -1, -1));
        addButton = new JButton();
        addButton.setText("增加映射");
        folderMapPanel.add(addButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        folderMapPanel.add(spacer1, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        folderMapPanel.add(spacer2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        removeButton = new JButton();
        removeButton.setText("删除映射");
        folderMapPanel.add(removeButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        table1.setDropMode(DropMode.ON_OR_INSERT_ROWS);
        table1.setSurrendersFocusOnKeystroke(false);
        folderMapPanel.add(table1, new GridConstraints(1, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 1, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return folderMapPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        table1 = new JTable();
        table1.setModel(new DefaultTableModel(
                new Object[][]{
                        {1, 2},
                        {1, 2},
                        {1, 2},
                        {1, 2},
                        {1, 2},
                        {1, 2},
                },
                new String[]{
                        "Java\u6E90\u8DEF\u5F84", "TypeScript\u76EE\u6807\u8DEF\u5F84"
                }
        ));

        table1.setBounds(0, 0, 400, 180);
        table1.setVisible(true);
    }
}
